// 30-Day CEFR B1 Reading Curriculum Data - High Variety, High Word Count
const challengeData = [
  {
    day: 1,
    title: "The Magic of Cinema",
    difficulty: "B1.1 Intermediate",
    story: "In December eighteen ninety-five, the Lumière brothers held the very first public screening of moving pictures in Paris. This revolutionary event completely transformed modern entertainment. Early spectators were so astounded by the realistic illusion of an oncoming train that some reportedly ran to the back of the room in panic. Over the following decades, cinema rapidly evolved from simple silent short clips into a highly sophisticated global art form, combining complex visual storytelling with musical scores and special effects to evoke deep human emotions.",
    target_words: ["revolutionary", "illusion", "spectator"],
    dictionary: {
      "held": "عقد / أقام",
      "public": "عمومي / علني",
      "screening": "عرض (سينمائي)",
      "moving": "متحرك",
      "pictures": "صور",
      "revolutionary": "ثوري",
      "event": "حدث / مناسبة",
      "completely": "تماماً / بالكامل",
      "transformed": "حوّل / غيّر",
      "modern": "حديث / معاصر",
      "entertainment": "ترفيه / تسلية",
      "early": "مبكر / أوائل",
      "spectators": "المتفرجون / المشاهدون",
      "astounded": "مذهولون / مندهشون",
      "realistic": "واقعي",
      "illusion": "وهم / خيال",
      "oncoming": "قادم / مقترب",
      "train": "قطار",
      "reportedly": "حسبما ورد / يقال",
      "ran": "ركض / جرى",
      "panic": "ذعر / هلع",
      "following": "تالي / لاحق",
      "decades": "عقود",
      "cinema": "السينما",
      "rapidly": "بسرعة / على نحو سريع",
      "evolved": "تطور / ارتقى",
      "simple": "بسيط",
      "silent": "صامت",
      "short": "قصير",
      "clips": "مقاطع",
      "highly": "للغاية / جداً",
      "sophisticated": "راقٍ / متطور معقد",
      "global": "عالمي",
      "art": "فن",
      "form": "شكل / قالب",
      "combining": "دمج / جمع",
      "complex": "معقد",
      "visual": "بصري",
      "storytelling": "سرد القصص",
      "musical": "موسيقي",
      "scores": "ألحان / موسيقى تصويرية",
      "special": "خاص",
      "effects": "مؤثرات",
      "evoke": "يثير / يستحضر",
      "deep": "عميق",
      "human": "بشري",
      "emotions": "عواطف / مشاعر",
      "spectator": "مشاهد / متفرج"
    },
    quiz: [
      { question: "What did the first public screening in Paris feature?", options: ["Colored animated drawings", "Moving pictures", "Live theatrical plays"], answer: 1 },
      { question: "How did early spectators react to the oncoming train illusion?", options: ["They laughed out loud", "Some ran to the back of the room in panic", "They demanded a refund"], answer: 1 }
    ]
  },
  {
    day: 2,
    title: "Deep Space Explorers",
    difficulty: "B1.1 Intermediate",
    story: "Astronomers have long dreamed of observing the universe without the blurry interference of Earth's atmosphere. This dream became a reality when high-tech telescopes were sent into space, orbiting high above our planet. These incredible devices capture crystal-clear images of distant galaxies, dying stars, and mysterious black holes. By studying the atmospheric data and radiation patterns from these deep space explorers, scientists can investigate how the universe was born and discover whether habitable planets exist in remote solar systems.",
    target_words: ["orbiting", "atmospheric", "phenomenon"],
    dictionary: {
      "astronomers": "علماء الفلك",
      "dreamed": "حلموا",
      "observing": "مراقبة / رصد",
      "universe": "الكون",
      "without": "بدون",
      "blurry": "ضبابي / غير واضح",
      "interference": "تداخل / تشويش",
      "atmosphere": "الغلاف الجوي",
      "became": "أصبح",
      "reality": "واقع",
      "high-tech": "تقنية عالية",
      "telescopes": "تلسكوبات / مقارب",
      "sent": "أُرسلت",
      "orbiting": "يدور في مدار",
      "above": "فوق",
      "planet": "كوكب",
      "incredible": "مذهل / لا يصدق",
      "devices": "أجهزة",
      "capture": "التقاط / يصور",
      "images": "صور",
      "distant": "بعيد",
      "galaxies": "مجرات",
      "dying": "يحتضر / ينطفئ",
      "stars": "نجوم",
      "mysterious": "غامض",
      "black": "أسود",
      "holes": "ثقوب",
      "studying": "دراسة",
      "atmospheric": "جوي / متعلق بالغلاف الجوي",
      "data": "بيانات / معلومات",
      "radiation": "إشعاع",
      "patterns": "أنماط",
      "scientists": "علماء",
      "investigate": "يتحقق / يستقصي",
      "born": "ولد / نشأ",
      "discover": "يكتشف",
      "whether": "ما إذا كان",
      "habitable": "صالح للسكن / العيش",
      "exist": "موجود / يتواجد",
      "remote": "بعيد / ناءٍ",
      "solar": "شمسي",
      "systems": "أنظمة",
      "phenomenon": "ظاهرة"
    },
    quiz: [
      { question: "Why did astronomers want telescopes in space?", options: ["To protect them from rain", "To avoid Earth's blurry atmospheric interference", "To make them closer to the sun"], answer: 1 },
      { question: "What can scientists investigate using deep space data?", options: ["How the universe was born and habitable planets", "How to control weather on Earth", "The migration of ocean creatures"], answer: 0 }
    ]
  },
  {
    day: 3,
    title: "Secret World of Octopuses",
    difficulty: "B1.1 Intermediate",
    story: "Octopuses are among the most fascinating creatures in the deep ocean. Unlike most invertebrates, they possess remarkable intelligence, capable of solving complex mazes and opening sealed jars to reach food. Their most spectacular ability is camouflage. By changing both the color and texture of their skin in milliseconds, they can blend perfectly with surrounding rocks and seaweed. This clever defense mechanism allows them to hide from dangerous predators and hunt for crabs silently in their harsh marine environment.",
    target_words: ["camouflage", "intelligence", "environment"],
    dictionary: {
      "among": "من بين / وسط",
      "fascinating": "ساحر / رائع جداً",
      "creatures": "مخلوقات",
      "deep": "عميق",
      "ocean": "محيط",
      "unlike": "على عكس",
      "invertebrates": "اللافقاريات",
      "possess": "يمتلك / يحوز",
      "remarkable": "ملحوظ / استثنائي",
      "intelligence": "ذكاء",
      "capable": "قادر على",
      "solving": "حل",
      "mazes": "متاهات",
      "opening": "فتح",
      "sealed": "مغلق بإحكام",
      "jars": "مرطبانات / أوعية",
      "reach": "الوصول إلى",
      "food": "طعام",
      "spectacular": "مذهل / رائع",
      "ability": "قدرة / مهارة",
      "camouflage": "تمويه / تخفٍّ",
      "changing": "تغيير",
      "color": "لون",
      "texture": "ملمس / بنية",
      "skin": "جلد",
      "milliseconds": "أجزاء من الثانية",
      "blend": "يمتزج / يندمج",
      "perfectly": "بشكل مثالي",
      "surrounding": "محيط",
      "rocks": "صخور",
      "seaweed": "أعشاب بحرية",
      "clever": "ذكي / بارع",
      "defense": "دفاع",
      "mechanism": "آلية / طريقة",
      "allows": "يسمح لـ",
      "hide": "يختبئ",
      "dangerous": "خطير",
      "predators": "مفترسات / حيوانات مفترسة",
      "hunt": "يصطاد",
      "crabs": "سلطعونات / كابوريا",
      "silently": "بصمت",
      "harsh": "قاسٍ",
      "marine": "بحري",
      "environment": "بيئة"
    },
    quiz: [
      { question: "What makes octopuses stand out from most other invertebrates?", options: ["They have sharp teeth", "They possess remarkable intelligence", "They can fly short distances"], answer: 1 },
      { question: "How do octopuses camouflage themselves?", options: ["By spraying thick black ink", "By changing skin color and texture in milliseconds", "By hiding inside abandoned shells"], answer: 1 }
    ]
  },
  {
    day: 4,
    title: "Ancient Rome's Aqueducts",
    difficulty: "B1.1 Intermediate",
    story: "Over two thousand years ago, Roman engineers built a massive network of stone channels called aqueducts to transport fresh water. Rather than using pumps, these structures relied entirely on the natural force of gravity. Engineers calculated incredibly gentle slopes so water would flow steadily across mountains and valleys. This massive system supplied millions of gallons of water daily to public baths, decorative fountains, and private homes, establishing a high standard of hygiene and engineering that amazed other ancient civilizations.",
    target_words: ["aqueducts", "gravity", "distribution"],
    dictionary: {
      "built": "بنوا",
      "massive": "ضخم / هائل",
      "network": "شبكة",
      "stone": "حجري",
      "channels": "قنوات",
      "aqueducts": "قنوات مائية / قناطر",
      "transport": "نقل",
      "fresh": "عذب / طازج",
      "water": "ماء",
      "rather": "بدلاً من",
      "pumps": "مضخات",
      "structures": "هياكل / أبنية",
      "relied": "اعتمدت",
      "entirely": "بالكامل",
      "natural": "طبيعي",
      "force": "قوة",
      "gravity": "جاذبية",
      "calculated": "حسبوا / خططوا دقيقاً",
      "incredibly": "بشكل لا يصدق",
      "gentle": "خفيف / تدريجي (منحدر)",
      "slopes": "منحدرات",
      "flow": "يتدفق / يجري",
      "steadily": "بثبات / بانتظام",
      "across": "عبر",
      "mountains": "جبال",
      "valleys": "وديان",
      "system": "نظام",
      "supplied": "زود / أمدّ",
      "millions": "ملايين",
      "gallons": "جالونات",
      "daily": "يومياً",
      "baths": "حمامات",
      "decorative": "تزيينية / جمالية",
      "fountains": "نوافير",
      "private": "خاص",
      "homes": "منازل",
      "establishing": "تأسيس / إرساء",
      "high": "مرتفع",
      "standard": "معيار / مستوى",
      "hygiene": "النظافة الشخصية / العامة",
      "engineering": "الهندسة",
      "amazed": "أذهل / أثار إعجاب",
      "ancient": "قديم",
      "civilizations": "حضارات",
      "distribution": "توزيع"
    },
    quiz: [
      { question: "How did Roman aqueducts transport water without pumps?", options: ["Using trained horses", "Relying entirely on the natural force of gravity", "Using underground steam engines"], answer: 1 },
      { question: "What did the aqueduct system supply water to?", options: ["Public baths, fountains, and private homes", "Large agricultural wheat farms only", "Military warships in the harbor"], answer: 0 }
    ]
  },
  {
    day: 5,
    title: "The Mediterranean Diet",
    difficulty: "B1.1 Intermediate",
    story: "Nutritionists often praise the Mediterranean diet for its incredible health benefits. Inspired by traditional eating habits in countries like Italy and Greece, this lifestyle focuses on fresh, whole ingredients. Key elements include abundant olive oil, colorful vegetables, whole grains, and lean proteins like fresh fish. Research shows this pattern is highly beneficial in preventing heart diseases and boosting brain function. Rather than emphasizing strict calorie restrictions, it encourages enjoying flavorful food with family, contributing to happiness and longevity.",
    target_words: ["ingredients", "beneficial", "longevity"],
    dictionary: {
      "nutritionists": "أخصائيو التغذية",
      "often": "غالباً",
      "praise": "يمدحون / يثنون على",
      "diet": "نظام غذائي",
      "incredible": "مذهل / رائع",
      "health": "صحي",
      "benefits": "فوائد",
      "inspired": "مستوحى من",
      "traditional": "تقليدي",
      "eating": "تناول الطعام",
      "habits": "عادات",
      "countries": "دول / بلدان",
      "lifestyle": "نمط حياة",
      "focuses": "يركز",
      "fresh": "طازج",
      "whole": "كامل / غير معالج",
      "ingredients": "مكونات / عناصر",
      "key": "رئيسي / أساسي",
      "elements": "عناصر",
      "include": "يشمل",
      "abundant": "وفير / غزير",
      "olive": "زيتون",
      "oil": "زيت",
      "vegetables": "خضروات",
      "grains": "حبوب",
      "lean": "خالٍ من الدهون",
      "proteins": "بروتينات",
      "fish": "سمك",
      "research": "أبحاث / دراسات",
      "shows": "تظهر",
      "pattern": "نمط",
      "beneficial": "مفيد / نافع",
      "preventing": "منع",
      "heart": "القلب",
      "diseases": "أمراض",
      "boosting": "تعزيز / تحسين",
      "brain": "دماغ",
      "function": "وظيفة",
      "emphasizing": "التأكيد على",
      "strict": "صارم / دقيق",
      "calorie": "سعرات حرارية",
      "restrictions": "قيود",
      "encourages": "يشجع",
      "enjoying": "الاستمتاع بـ",
      "flavorful": "لذيذ / مليء بالنكهة",
      "food": "طعام",
      "family": "عائلة",
      "contributing": "المساهمة في",
      "happiness": "سعادة",
      "longevity": "طول العمر"
    },
    quiz: [
      { question: "Which region's traditional eating habits inspired this diet?", options: ["Northern Europe", "Mediterranean countries like Italy and Greece", "East Asia"], answer: 1 },
      { question: "What is emphasized in this lifestyle instead of strict calorie counting?", options: ["Drinking carbonated beverages", "Enjoying flavorful food with family", "Eating only once a day"], answer: 1 }
    ]
  },
  {
    day: 6,
    title: "The Mystery of Auroras",
    difficulty: "B1.1 Intermediate",
    story: "The Northern and Southern Lights, scientifically known as auroras, are among nature's most spectacular displays. These glowing ribbons of green, violet, and red light occur when charged solar particles collide with gases in Earth's magnetic field. These dramatic collisions excite the atmospheric atoms, causing them to emit colorful light high in the night sky. While ancient communities created beautiful myths about sky spirits and celestial fires, modern science reveals how our planet interacts with the solar wind.",
    target_words: ["collisions", "particles", "spectacular"],
    dictionary: {
      "northern": "شمالي",
      "southern": "جنوبي",
      "lights": "أضواء",
      "scientifically": "علمياً",
      "known": "معروف",
      "auroras": "الشفق القطبي",
      "glowing": "متوهج",
      "ribbons": "أشرطة",
      "light": "ضوء",
      "occur": "تحدث / تقع",
      "charged": "مشحونة",
      "solar": "شمسي",
      "particles": "جسيمات",
      "collide": "تتصادم",
      "gases": "غازات",
      "magnetic": "مغناطيسي",
      "field": "حقل / مجال",
      "dramatic": "مثير / درامي",
      "collisions": "تصادمات",
      "excite": "تثير / تنشط",
      "atoms": "ذرات",
      "causing": "مسببة",
      "emit": "تنبعث / تطلق",
      "colorful": "ملون",
      "night": "ليل",
      "sky": "سماء",
      "while": "بينما / على الرغم من",
      "ancient": "قديم",
      "communities": "مجتمعات",
      "created": "صنعت / ابتكرت",
      "beautiful": "جميل",
      "myths": "أساطير",
      "spirits": "أرواح",
      "celestial": "سماوي",
      "fires": "نيران",
      "science": "علم",
      "reveals": "يكشف",
      "interacts": "يتفاعل",
      "wind": "رياح",
      "spectacular": "مذهل / رائع"
    },
    quiz: [
      { question: "What scientific event causes the auroras to occur?", options: ["Volcanic eruptions at the poles", "Charged solar particles colliding with magnetic field gases", "Heavy winter snowfalls reflect moonlight"], answer: 1 },
      { question: "What colors are commonly seen in these light displays?", options: ["Only black and white", "Green, violet, and red", "Orange and brown"], answer: 1 }
    ]
  },
  {
    day: 7,
    title: "The Enigma Machine",
    difficulty: "B1.1 Intermediate",
    story: "During World War Two, the German military used a highly complex device called the Enigma machine to protect their secret messages. This advanced typewriter encrypted words into seemingly random letters using rotating wheels. Because the internal wiring changed with every single letter typed, the code was considered completely unbreakable. However, a brilliant team of mathematicians, led by Alan Turing, built early mechanical computers to crack the cipher. This secret intelligence breakthrough shortened the war by years, saving countless lives.",
    target_words: ["encrypted", "cipher", "decipher"],
    dictionary: {
      "during": "خلال / أثناء",
      "military": "عسكري",
      "used": "استخدم",
      "device": "جهاز / آلة",
      "enigma": "لغز / إنيجما",
      "machine": "آلة",
      "protect": "حماية",
      "secret": "سري",
      "messages": "رسائل",
      "advanced": "متقدم / متطور",
      "typewriter": "آلة كاتبة",
      "encrypted": "مشفر",
      "words": "كلمات",
      "seemingly": "تبدو ظاهرياً",
      "random": "عشوائي",
      "letters": "حروف",
      "rotating": "دوارة / تدور",
      "wheels": "عجلات / بكرات",
      "internal": "داخلي",
      "wiring": "توصيلات الأسلاك",
      "changed": "تغيرت",
      "single": "فردي / واحد",
      "typed": "مكتوب / مطبوع",
      "code": "شفرة / رمز",
      "considered": "اعتُبر",
      "completely": "تماماً",
      "unbreakable": "غير قابل للكسر / الاختراق",
      "however": "ومع ذلك",
      "brilliant": "عبقري / متألق",
      "team": "فريق",
      "mathematicians": "علماء الرياضيات",
      "led": "بقيادة / يقوده",
      "mechanical": "ميكانيكي",
      "computers": "حواسيب",
      "crack": "كسر / فك (الشفرة)",
      "cipher": "الشفرة / الرمز السري",
      "intelligence": "معلومات استخباراتية / ذكاء",
      "breakthrough": "إنجاز / طفرة",
      "shortened": "قصر / اختصر",
      "war": "حرب",
      "years": "سنوات",
      "saving": "إنقاذ / توفير",
      "countless": "لا يحصى / لا يعد",
      "lives": "أرواح / حياة البشر",
      "decipher": "يفك شفرة / يحلل"
    },
    quiz: [
      { question: "Why was the Enigma code considered unbreakable?", options: ["It was written in a rare dead language", "The internal wiring changed with every letter typed", "The messages were delivered by eagles"], answer: 1 },
      { question: "Who led the mathematical team that cracked the cipher?", options: ["Lumière brothers", "Alan Turing", "Vincent van Gogh"], answer: 1 }
    ]
  },
  {
    day: 8,
    title: "Madagascar's Wildlife",
    difficulty: "B1.2 Intermediate",
    story: "Located off the eastern coast of Africa, Madagascar is the world's fourth largest island. Because it separated from other landmasses eighty-eight million years ago, its wildlife evolved in complete isolation. As a result, approximately ninety percent of its plants and animals are found nowhere else on Earth. The most famous residents are lemurs, a unique group of primates. Sadly, deforestation and agricultural expansion pose an extreme threat to these unique species, prompting international conservation groups to establish secure natural reserves.",
    target_words: ["isolated", "evolution", "endangered"],
    dictionary: {
      "located": "يقع",
      "coast": "ساحل",
      "island": "جزيرة",
      "separated": "انفصلت",
      "landmasses": "كتل برية / قارات",
      "million": "مليون",
      "wildlife": "الحياة البرية",
      "evolved": "تطورت",
      "isolation": "عزلة",
      "result": "نتيجة",
      "approximately": "تقريباً",
      "percent": "بالمئة",
      "found": "موجود / يعثر عليه",
      "nowhere": "لا مكان",
      "else": "آخر",
      "earth": "الأرض",
      "famous": "مشهور",
      "residents": "سكان / قاطنون",
      "lemurs": "حيوانات الليمور",
      "unique": "فريد من نوعه",
      "primates": "الرئيسيات",
      "sadly": "للأسف",
      "deforestation": "إزالة الغابات",
      "agricultural": "زراعي",
      "expansion": "توسع",
      "pose": "يشكل",
      "extreme": "شديد / أقصى",
      "threat": "تهديد",
      "species": "أنواع / فصائل",
      "prompting": "يدفع / يحفز",
      "international": "دولي",
      "conservation": "حفظ الطبيعة / حماية البيئة",
      "groups": "مجموعات",
      "establish": "تأسيس / إنشاء",
      "secure": "آمن",
      "reserves": "محميات طبيعية",
      "isolated": "معزول",
      "evolution": "التطور / نشوء",
      "endangered": "مهدد بالانقراض"
    },
    quiz: [
      { question: "Why are ninety percent of Madagascar's species unique to the island?", options: ["The island has extreme cold weather", "It evolved in complete isolation for millions of years", "Humans imported them recently"], answer: 1 },
      { question: "What is the primary threat to Madagascan lemurs today?", options: ["Rising sea levels", "Deforestation and agricultural expansion", "Predator fish"], answer: 1 }
    ]
  },
  {
    day: 9,
    title: "Earthquake-Proof Buildings",
    difficulty: "B1.2 Intermediate",
    story: "In areas prone to intense seismic activity, engineers must design buildings capable of surviving sudden ground movements. Instead of making structures rigid, modern architecture focuses on flexibility. Many skyscrapers are built on specialized rubber pads that act as shock absorbers, isolating the foundation from the shaking ground. Additionally, giant heavy pendulums are suspended near the top of tall buildings. When an earthquake sways the skyscraper, the pendulum swings in the opposite direction, neutralizing the dangerous motion.",
    target_words: ["seismic", "foundation", "absorb"],
    dictionary: {
      "areas": "مناطق",
      "prone": "عرضة لـ / مائل إلى",
      "intense": "شديد / قوي",
      "seismic": "زلزالي",
      "activity": "نشاط",
      "engineers": "مهندسون",
      "design": "تصميم",
      "buildings": "مباني",
      "capable": "قادر على",
      "surviving": "البقاء / النجاة",
      "sudden": "مفاجئ",
      "ground": "الأرض / الأرضية",
      "movements": "تحركات",
      "instead": "بدلاً من",
      "making": "جعل",
      "rigid": "صلب / صلد",
      "architecture": "الهندسة المعمارية",
      "focuses": "يركز",
      "flexibility": "مرونة",
      "skyscrapers": "ناطحات سحاب",
      "built": "مبنية",
      "specialized": "متخصص",
      "rubber": "مطاطي",
      "pads": "وسائد / قواعد",
      "act": "تعمل / تقوم بدور",
      "shock": "صدمة",
      "absorbers": "ممتصات",
      "isolating": "عزل",
      "foundation": "أساس / قاعدة المبنى",
      "shaking": "مهتز",
      "additionally": "بالإضافة إلى ذلك",
      "giant": "عملاق",
      "heavy": "ثقيل",
      "pendulums": "نواسات / بندول",
      "suspended": "معلق",
      "top": "أعلى / قمة",
      "tall": "شاهق / طويل",
      "earthquake": "زلزال",
      "sways": "يميل / يهتز",
      "swings": "يتأرجح",
      "opposite": "معاكس",
      "direction": "اتجاه",
      "neutralizing": "إبطال مفعول / موازنة",
      "motion": "حركة",
      "absorb": "يمتص"
    },
    quiz: [
      { question: "What is the key approach of modern architecture to seismic design?", options: ["Building extremely rigid brick walls", "Focusing on flexibility and absorbing movement", "Constructing buildings below sea level"], answer: 1 },
      { question: "How does a giant pendulum at the top of a skyscraper protect it?", options: ["It generates wind power", "It swings in the opposite direction to neutralize motion", "It acts as an escape ladder"], answer: 1 }
    ]
  },
  {
    day: 10,
    title: "The Origin of Chocolate",
    difficulty: "B1.2 Intermediate",
    story: "Today, chocolate is a sweet treat enjoyed worldwide, but its history began thousands of years ago as a bitter ceremonial beverage. In ancient Mesoamerica, Mayan and Aztec civilizations cultivated cacao trees in the tropical rainforests. They ground the roasted seeds into a thick paste and mixed it with chili peppers and warm water. This valuable mixture was so highly prized that cacao beans were used as currency for trade. Only wealthy rulers and brave warriors were allowed to consume this divine drink.",
    target_words: ["ceremonial", "cultivated", "currency"],
    dictionary: {
      "today": "اليوم",
      "chocolate": "شوكولاتة",
      "sweet": "حلو",
      "treat": "حلوى / متعة",
      "enjoyed": "يستمتع بها",
      "worldwide": "في جميع أنحاء العالم",
      "history": "تاريخ",
      "began": "بدأ",
      "bitter": "مر",
      "ceremonial": "طقسي / احتفالي",
      "beverage": "مشروب",
      "ancient": "قديم",
      "mesoamerica": "أمريكا الوسطى القديمة",
      "mayan": "المايا",
      "aztec": "الأزتك",
      "civilizations": "حضارات",
      "cultivated": "زرعوا / فلحوا",
      "cacao": "كاكاو",
      "trees": "أشجار",
      "tropical": "استوائي",
      "rainforests": "غابات مطيرة",
      "ground": "طحنوا",
      "roasted": "محمص",
      "seeds": "بذور",
      "paste": "عجينة / معجون",
      "mixed": "خلطوه",
      "chili": "فلفل حار",
      "peppers": "فلفل",
      "warm": "دافئ",
      "valuable": "ثمين / ذو قيمة",
      "mixture": "مزيج / خليط",
      "highly": "للغاية",
      "prized": "مقدر / مثمن",
      "beans": "حبوب / قرون",
      "used": "استخدمت",
      "currency": "عملة / وسيلة دفع",
      "trade": "تجارة",
      "only": "فقط",
      "wealthy": "أثرياء",
      "rulers": "حكام",
      "brave": "شجعان",
      "warriors": "محاربون",
      "allowed": "مسموح لهم",
      "consume": "يستهلك / يتناول",
      "divine": "مقدس / إلهي",
      "drink": "مشروب"
    },
    quiz: [
      { question: "What did the ancient Mesoamericans mix cacao paste with?", options: ["Sugar and sweet honey", "Chili peppers and warm water", "Milk and vanilla"], answer: 1 },
      { question: "How did Mayan and Aztec societies use cacao beans besides food?", options: ["As building bricks for pyramids", "As currency for trading goods", "To make colorful clothing dye"], answer: 1 }
    ]
  },
  {
    day: 11,
    title: "The Placebo Effect",
    difficulty: "B1.2 Intermediate",
    story: "In medical science, the placebo effect is a fascinating psychological phenomenon. It occurs when patients show real physical health improvements after taking inactive treatments, such as a simple sugar pill or water injection. Because patients firmly believe they are receiving potent medicine, their brains release chemicals that reduce pain and lower stress. Doctors utilize placebos in clinical trials to measure the true efficacy of newly developed drugs, showing how closely our minds are linked to physical healing.",
    target_words: ["psychological", "efficacy", "improvement"],
    dictionary: {
      "medical": "طبي",
      "science": "علم",
      "placebo": "العلاج الوهمي / البلاسيبو",
      "effect": "تأثير / مفعول",
      "fascinating": "مثير للاهتمام",
      "psychological": "نفسي",
      "phenomenon": "ظاهرة",
      "occurs": "تحدث",
      "patients": "مرضى",
      "show": "يظهرون",
      "real": "حقيقي",
      "physical": "جسدي / بدني",
      "improvements": "تحسن / تطورات إيجابية",
      "after": "بعد",
      "taking": "تناول / أخذ",
      "inactive": "غير فعال / خامل",
      "treatments": "علاجات",
      "simple": "بسيط",
      "sugar": "سكر",
      "pill": "حبة دواء / قرص",
      "injection": "حقنة / إبرة",
      "firmly": "بشدة / بثبات",
      "believe": "يعتقدون",
      "receiving": "يتلقون",
      "potent": "قوي / فعال",
      "medicine": "دواء",
      "brains": "أدمغة",
      "release": "تفرز",
      "chemicals": "مواد كيميائية",
      "reduce": "تقلل",
      "pain": "ألم",
      "lower": "تخفض",
      "stress": "توتر",
      "doctors": "أطباء",
      "utilize": "يستخدمون / يوظفون",
      "placebos": "العلاجات الوهمية",
      "clinical": "سريري / عيادي",
      "trials": "تجارب",
      "measure": "قياس",
      "true": "حقيقي",
      "efficacy": "فعالية / جدوى",
      "newly": "حديثاً",
      "developed": "طُوّرت",
      "drugs": "عقاقير / أدوية",
      "closely": "عن كثب / وثيقاً",
      "minds": "عقول",
      "linked": "مرتبطة",
      "healing": "شفاء / تعافي",
      "improvement": "تحسن"
    },
    quiz: [
      { question: "What is a placebo?", options: ["An inactive treatment like a sugar pill", "A rare herbal cure from the forest", "A robotic surgical machine"], answer: 0 },
      { question: "Why do placebos cause real physical improvements?", options: ["They contain highly complex vitamins", "The patient's belief triggers brain chemicals that lower pain", "They modify human DNA structures"], answer: 1 }
    ]
  },
  {
    day: 12,
    title: "Scaling Mount Everest",
    difficulty: "B1.2 Intermediate",
    story: "Mount Everest is the highest peak on Earth, towering high in the Himalayan range. Climbing this dangerous peak requires incredible physical endurance and months of planning. At extreme altitudes, the air becomes thin, making it difficult to breathe. Mountaineers must spend weeks in base camps to acclimatize their bodies before attempting the summit. Despite freezing temperatures, strong winds, and deep ice crevices, hundreds of adventurers travel to Nepal annually, driven by determination to conquer the highest point on our planet.",
    target_words: ["altitude", "acclimatize", "determination"],
    dictionary: {
      "highest": "أعلى / شاهق الأقصى",
      "peak": "قمة جبلية",
      "towering": "شامخ / شاهق",
      "climbing": "تسلق",
      "requires": "يتطلب",
      "physical": "بدني / جسدي",
      "endurance": "قدرة التحمل",
      "months": "أشهر",
      "planning": "تخطيط",
      "extreme": "أقصى / شديد",
      "altitudes": "ارتفاعات عن سطح البحر",
      "air": "هواء",
      "thin": "خفيف / رقيق",
      "making": "يجعل",
      "difficult": "صعب",
      "breathe": "يتنفس",
      "mountaineers": "متسلقو الجبال",
      "spend": "يقضون",
      "weeks": "أسابيع",
      "base": "قاعدة",
      "camps": "مخيمات",
      "acclimatize": "يتأقلم / يتكيف",
      "bodies": "أجسام",
      "before": "قبل",
      "attempting": "محاولة",
      "summit": "القمة",
      "despite": "على الرغم من",
      "freezing": "متجمد / قارص",
      "temperatures": "درجات حرارة",
      "strong": "قوي",
      "winds": "رياح",
      "ice": "جليد / ثلج",
      "crevices": "شقوق عميقة",
      "hundreds": "مئات",
      "adventurers": "مغامرون",
      "travel": "يسافرون",
      "nepal": "نيبال",
      "annually": "سنوياً",
      "driven": "مدفوعين بـ",
      "determination": "عزيمة / تصميم",
      "conquer": "قهر / غزو / صعود",
      "planet": "كوكب",
      "altitude": "الارتفاع"
    },
    quiz: [
      { question: "Why is breathing difficult near the summit of Mount Everest?", options: ["The air is filled with volcanic dust", "The air becomes extremely thin at high altitudes", "High winds block the mouth"], answer: 1 },
      { question: "What do climbers do at base camps for several weeks?", options: ["They build comfortable log cabins", "They acclimatize their bodies to the high altitude", "They wait for Nepal's summer festival"], answer: 1 }
    ]
  },
  {
    day: 13,
    title: "Carnivorous Plants",
    difficulty: "B1.2 Intermediate",
    story: "In boggy wetlands where the soil lacks essential minerals, some unusual plants have developed a carnivorous lifestyle to survive. The most famous is the Venus flytrap. This brilliant plant has specialized leaves that snap shut when small insects trigger sensitive hairs. Once captured, the plant secretes enzymes to slowly digest the prey, absorbing critical nutrients like nitrogen. These unusual biological adaptations prove how plants can evolve innovative behaviors to thrive in highly challenging environmental conditions.",
    target_words: ["carnivorous", "digest", "nutrients"],
    dictionary: {
      "boggy": "مستنقعي / وحل",
      "wetlands": "أراضٍ رطبة",
      "where": "حيث",
      "soil": "تربة",
      "lacks": "تفتقر إلى / ينقصها",
      "essential": "أساسي",
      "minerals": "معادن",
      "unusual": "غير مألوف / غريب",
      "plants": "نباتات",
      "developed": "طورت",
      "carnivorous": "آكل لحوم / مفترس",
      "lifestyle": "نمط حياة",
      "survive": "البقاء / النجاة",
      "famous": "مشهور",
      "venus": "فينوس / الزهرة",
      "flytrap": "صائدة الذباب",
      "brilliant": "رائع / بارع",
      "specialized": "متخصص / متحور",
      "leaves": "أوراق",
      "snap": "تنطبق / تغلق بقوة",
      "shut": "مغلق",
      "small": "صغير",
      "insects": "حشرات",
      "trigger": "تلمس / تحفز",
      "sensitive": "حساس",
      "hairs": "شعيرات",
      "captured": "يتم صيده",
      "secretes": "تفرز",
      "enzymes": "إنزيمات",
      "slowly": "ببطء",
      "digest": "تهضم",
      "prey": "فريسة",
      "absorbing": "امتصاص",
      "critical": "حاسم / حيوي",
      "nutrients": "مغذيات / مواد غذائية",
      "nitrogen": "نيتروجين",
      "biological": "بيولوجي / حيوي",
      "adaptations": "تكيفات",
      "prove": "تثبت",
      "evolve": "تتطور",
      "innovative": "مبتكر",
      "behaviors": "سلوكيات",
      "thrive": "تزدهر",
      "challenging": "صعب / مليء بالتحديات",
      "environmental": "بيئي",
      "conditions": "ظروف"
    },
    quiz: [
      { question: "Why did some plants evolve to become carnivorous?", options: ["They did not like the taste of soil", "To get nutrients lacking in boggy soils", "To defend themselves from grazing cows"], answer: 1 },
      { question: "How does a Venus flytrap detect its prey?", options: ["Using small compound eyes", "When insects trigger its sensitive leaf hairs", "Through sweet flower scent only"], answer: 1 }
    ]
  },
  {
    day: 14,
    title: "The Orient Express",
    difficulty: "B1.2 Intermediate",
    story: "In eighteen eighty-three, the legendary Orient Express began its inaugural journey, offering a luxurious passenger experience that linked Paris to Constantinople. Known as the 'King of Trains', it attracted wealthy travelers, royal figures, and famous writers. The train featured polished mahogany wood, velvet armchairs, and exquisite dining rooms serving fine French meals. This traveling hotel was not merely a convenient way to cross Europe; it offered a mysterious, charming atmosphere that inspired countless novels and shaped modern luxury travel.",
    target_words: ["luxurious", "passenger", "atmosphere"],
    dictionary: {
      "legendary": "أسطوري",
      "orient": "الشرق",
      "express": "السريع (قطار)",
      "inaugural": "افتتاحي / تدشين",
      "journey": "رحلة",
      "offering": "يقدم",
      "luxurious": "فاخر / فخم",
      "passenger": "مسافر / راكب",
      "experience": "تجربة",
      "linked": "ربط",
      "paris": "باريس",
      "constantinople": "القسطنطينية",
      "known": "معروف بـ",
      "king": "ملك",
      "trains": "قطارات",
      "attracted": "جذب",
      "wealthy": "أثرياء",
      "travelers": "مسافرين",
      "royal": "ملكي",
      "figures": "شخصيات",
      "writers": "كتاب",
      "featured": "تميز بـ / احتوى على",
      "polished": "مصقول / لامع",
      "mahogany": "خشب الماهوجني",
      "wood": "خشب",
      "velvet": "قطيفة / مخمل",
      "armchairs": "مقاعد وثيرية / فوتيه",
      "exquisite": "رائع الجمال / رقيق",
      "dining": "تناول الطعام",
      "rooms": "غرف",
      "serving": "تقدم",
      "fine": "فاخر / طيب",
      "meals": "وجبات",
      "traveling": "متنقل",
      "hotel": "فندق",
      "merely": "مجرد",
      "convenient": "مريح / ملائم",
      "way": "طريقة / وسيلة",
      "cross": "عبور / قطع",
      "europe": "أوروبا",
      "mysterious": "غامض",
      "charming": "ساحر / جذاب",
      "atmosphere": "أجواء / غلاف جوي",
      "inspired": "ألهم",
      "countless": "لا يحصى",
      "novels": "روايات",
      "shaped": "شكل / صاغ",
      "luxury": "رفاهية"
    },
    quiz: [
      { question: "Which cities did the original Orient Express link?", options: ["London and Rome", "Paris and Constantinople", "Berlin and Moscow"], answer: 1 },
      { question: "What materials were used inside the luxury cars?", options: ["Plastic and steel tables", "Polished mahogany wood and velvet armchairs", "Clay and stone benches"], answer: 1 }
    ]
  },
  {
    day: 15,
    title: "Deep Sea Hydrothermal Vents",
    difficulty: "B1.2 Intermediate",
    story: "In the absolute darkness of the ocean floor, scientists discovered hydrothermal vents. These deep sea geysers spew mineral-rich water heated by underground volcanic magma. Surprisingly, these hot zones host dense, highly productive ecosystems. Lacking any sunlight, marine creatures here cannot rely on plant photosynthesis. Instead, specialized bacteria perform chemosynthesis, converting toxic chemicals from the vents into energy. This unique marine ecosystem proves that complex organic life can thrive in conditions once thought completely inhabitable.",
    target_words: ["geothermal", "ecosystem", "synthetic"],
    dictionary: {
      "absolute": "مطلق / تام",
      "darkness": "ظلام",
      "floor": "قاع / أرضية",
      "scientists": "علماء",
      "discovered": "اكتشفوا",
      "hydrothermal": "حراري مائي",
      "vents": "فتحات / فوهات",
      "sea": "بحر",
      "geysers": "ينابيع حارة",
      "spew": "تنفث / تقذف",
      "mineral-rich": "غني بالمعادن",
      "heated": "مسخن",
      "underground": "تحت الأرض",
      "volcanic": "بركاني",
      "magma": "صهارة",
      "surprisingly": "للمفاجأة",
      "hot": "ساخن",
      "zones": "مناطق",
      "host": "تستضيف / تحتضن",
      "dense": "كثيف",
      "productive": "منتج / حيوي",
      "ecosystems": "أنظمة بيئية",
      "lacking": "يفتقر إلى",
      "sunlight": "ضوء الشمس",
      "marine": "بحري",
      "creatures": "مخلوقات",
      "rely": "تعتمد",
      "photosynthesis": "البناء الضوئي",
      "instead": "بدلاً من ذلك",
      "bacteria": "بكتيريا",
      "perform": "تؤدي",
      "chemosynthesis": "التمثيل الكيميائي",
      "converting": "تحويل",
      "toxic": "سام",
      "chemicals": "مواد كيميائية",
      "energy": "طاقة",
      "unique": "فريد",
      "organic": "عضوي",
      "life": "حياة",
      "thrive": "تزدهر",
      "conditions": "ظروف",
      "thought": "اعتقدت",
      "completely": "تماماً",
      "inhabitable": "غير صالح للعيش (هنا مقصود بها العكس)",
      "geothermal": "حراري أرضي",
      "ecosystem": "النظام البيئي",
      "synthetic": "اصطناعي / تخليقي"
    },
    quiz: [
      { question: "How is water heated at hydrothermal vents?", options: ["By high-intensity surface sunlight", "By underground volcanic magma", "By electric currents from submarine cables"], answer: 1 },
      { question: "What process do vent bacteria use to generate energy instead of photosynthesis?", options: ["Aerobic respiration", "Chemosynthesis using toxic chemicals", "Decomposing forest leaves"], answer: 1 }
    ]
  },
  {
    day: 16,
    title: "Vincent van Gogh",
    difficulty: "B1.2 Intermediate",
    story: "Vincent van Gogh is recognized as one of the most influential painters in Western art history. During his turbulent life, the Dutch master created over two thousand artworks, including vibrant landscapes, dramatic self-portraits, and iconic starry skies. His unique style utilized thick paint strokes and bold, expressive color palettes to convey deep inner sorrow and spiritual joy. Although he sold only a single painting during his lifetime and struggled with extreme mental illness, his revolutionary artistic vision redefined modern painting style.",
    target_words: ["turbulent", "expressive", "post-impressionist"],
    dictionary: {
      "recognized": "معترف به / مشهور",
      "influential": "مؤثر",
      "painters": "رسامون",
      "western": "غربي",
      "art": "فن",
      "history": "تاريخ",
      "during": "خلال",
      "turbulent": "مضطرب / عاصف",
      "life": "حياة",
      "dutch": "هولندي",
      "master": "سيد / عبقري",
      "created": "ابتكر / صنع",
      "artworks": "أعمال فنية",
      "including": "بما في ذلك",
      "vibrant": "حيوية / مفعم بالألوان",
      "landscapes": "مناظر طبيعية",
      "self-portraits": "بورتريهات شخصية / رسم ذاتي",
      "iconic": "أيقوني",
      "starry": "مرصع بالنجوم",
      "skies": "سموات",
      "style": "أسلوب / نمط",
      "utilized": "استخدم",
      "thick": "سميك / غليظ",
      "paint": "طلاء / ألوان",
      "strokes": "ضربات فرشاة",
      "bold": "جريء",
      "expressive": "تعبيري",
      "color": "لون",
      "palettes": "باليتات ألوان / مجموعات الألوان",
      "convey": "نقل / تعبير عن",
      "inner": "داخلي",
      "sorrow": "حزن / أسى",
      "spiritual": "روحي",
      "joy": "فرح / بهجة",
      "although": "بالرغم من",
      "sold": "باع",
      "single": "واحد / فردي",
      "painting": "لوحة",
      "lifetime": "حياة / عمر",
      "struggled": "كافح / عانى",
      "mental": "عقلي / نفسي",
      "illness": "مرض",
      "revolutionary": "ثوري",
      "artistic": "فني",
      "vision": "رؤية",
      "redefined": "أعاد تعريف",
      "post-impressionist": "ما بعد الانطباعية"
    },
    quiz: [
      { question: "How many paintings did Van Gogh reportedly sell during his lifetime?", options: ["Over two thousand", "Only a single painting", "None at all"], answer: 1 },
      { question: "What characterized Van Gogh's artistic style?", options: ["Monochrome black pencil sketches", "Thick paint strokes and bold, expressive colors", "Smooth, invisible brush lines"], answer: 1 }
    ]
  },
  {
    day: 17,
    title: "The Power of Fiber Optics",
    difficulty: "B1.2 Intermediate",
    story: "Deep beneath our oceans lies a complex web of glass cables that connects continents instantly. These fiber optic lines are the true backbone of the global internet. Instead of transmitting electrical signals through copper metal, they send rapid pulses of laser light down ultra-thin strands of pure glass. Because light travels at extreme speeds and suffers very little signal loss over long distances, fiber optics can carry massive amounts of communication bandwidth, enabling people to stream video and share global data seamlessly.",
    target_words: ["pulses", "transmitting", "bandwidth"],
    dictionary: {
      "lies": "يقع / يمتد",
      "complex": "معقد",
      "web": "شبكة",
      "glass": "زجاجي",
      "cables": "كابلات",
      "connects": "يربط",
      "continents": "قارات",
      "instantly": "فوراً",
      "fiber": "ألياف",
      "optic": "بصرية",
      "lines": "خطوط",
      "true": "حقيقي",
      "backbone": "العمود الفقري",
      "global": "عالمي",
      "internet": "إنترنت",
      "instead": "بدلاً من",
      "transmitting": "إرسال / نقل الإشارات",
      "electrical": "كهربائي",
      "signals": "إشارات",
      "through": "عبر",
      "copper": "نحاس",
      "metal": "معدن",
      "send": "ترسل",
      "pulses": "نبضات",
      "laser": "ليزر",
      "light": "ضوء",
      "down": "عبر / أسفل",
      "ultra-thin": "رقيق جداً / فائق الدقة",
      "strands": "خيوط / ألياف",
      "pure": "نقي",
      "travels": "يسافر / ينتقل",
      "speeds": "سرعات",
      "suffers": "يعاني / يتعرض لـ",
      "little": "قليل",
      "loss": "فقدان / ضعف",
      "distances": "مسافات",
      "carry": "تحمل / تنقل",
      "massive": "ضخم / هائل",
      "amounts": "كميات",
      "communication": "اتصالات",
      "bandwidth": "عرض النطاق الترددي / سعة البيانات",
      "enabling": "تمكين",
      "people": "ناس",
      "stream": "بث / مشاهدة مباشرة",
      "video": "فيديو",
      "share": "مشاركة",
      "seamlessly": "بسلاسة / بدون انقطاع"
    },
    quiz: [
      { question: "What materials do fiber optic cables use to carry signals?", options: ["Thick copper wiring", "Ultra-thin strands of pure glass", "Water pipes"], answer: 1 },
      { question: "How are messages transmitted through fiber optic cables?", options: ["Using sound waves", "Using rapid pulses of laser light", "Using high-pressure steam"], answer: 1 }
    ]
  },
  {
    day: 18,
    title: "Stoicism: Ancient Calm",
    difficulty: "B1.2 Intermediate",
    story: "Originating in ancient Athens, Stoicism is a practical philosophy designed to help individuals maintain calm in turbulent times. Famous thinkers like Marcus Aurelius argued that while we cannot control external circumstances, we have full power over our emotional responses. By separating events into what is within our control and what is not, we can avoid useless worry. This psychological resilience allows individuals to face difficult setbacks with courage and wisdom, prioritizing rational thinking over sudden emotional panic.",
    target_words: ["philosophy", "control", "resilience"],
    dictionary: {
      "originating": "نشأت في",
      "athens": "أثينا",
      "stoicism": "الفلسفة الرواقية",
      "practical": "عملي",
      "philosophy": "فلسفة",
      "designed": "مصممة لـ",
      "help": "مساعدة",
      "individuals": "أفراد / أشخاص",
      "maintain": "الحفاظ على",
      "calm": "هدوء",
      "turbulent": "مضطرب / عاصف",
      "times": "أوقات / أزمنة",
      "famous": "مشهور",
      "thinkers": "مفكرون",
      "marcus": "ماركوس",
      "aurelius": "أوريليوس",
      "argued": "جادل / ناقش",
      "while": "بينما",
      "control": "سيطرة / تحكم",
      "external": "خارجي",
      "circumstances": "ظروف",
      "full": "كامل",
      "power": "قوة / سلطة",
      "emotional": "عاطفي",
      "responses": "ردود أفعال",
      "separating": "فصل / تمييز",
      "events": "أحداث",
      "within": "ضمن / داخل",
      "avoid": "تجنب",
      "useless": "بلا فائدة / عديم الجدوى",
      "worry": "قلق",
      "psychological": "نفسي",
      "resilience": "مرونة نفسية / قدرة على التحمل",
      "allows": "تسمح لـ",
      "face": "يواجه",
      "difficult": "صعب",
      "setbacks": "عقبات / نكسات",
      "courage": "شجاعة",
      "wisdom": "حكمة",
      "prioritizing": "إعطاء الأولوية لـ",
      "rational": "عقلاني / منطقي",
      "thinking": "تفكير",
      "sudden": "مفاجئ",
      "panic": "ذعر"
    },
    quiz: [
      { question: "According to Stoicism, what do humans have full control over?", options: ["The weather and natural disasters", "Their own emotional responses and choices", "The actions of other people"], answer: 1 },
      { question: "How does Stoic philosophy suggest we handle external setbacks?", options: ["By ignoring them and sleeping", "With courage, wisdom, and rational thinking", "By showing anger and panic"], answer: 1 }
    ]
  },
  {
    day: 19,
    title: "The Mechanics of Tornadoes",
    difficulty: "B1.2 Intermediate",
    story: "Tornadoes are among Earth's most violent atmospheric storms, characterized by a rapidly spinning funnel of wind. They develop during severe thunderstorms when warm, moist air collides with cold, dry air. Under specific atmospheric conditions, these winds begin to rotate, forming a horizontal tube of spinning air. Strong updrafts tilt this rotating tube into a vertical column. Reaching extreme speeds of over three hundred miles per hour, they can cause massive devastation, destroying homes and lifting cars effortlessly.",
    target_words: ["atmospheric", "rotation", "devastation"],
    dictionary: {
      "tornadoes": "أعاصير قمعية",
      "among": "من بين",
      "violent": "عنيف",
      "atmospheric": "جوي",
      "storms": "عواصف",
      "characterized": "تتميز بـ",
      "rapidly": "بسرعة",
      "spinning": "دوار / يدور بسرعة",
      "funnel": "قمع",
      "wind": "رياح",
      "develop": "تنشأ / تتطور",
      "during": "خلال",
      "severe": "شديد / قاسي",
      "thunderstorms": "عواصف رعدية",
      "warm": "دافئ",
      "moist": "رطب",
      "collides": "يتصادم",
      "cold": "بارد",
      "dry": "جاف",
      "specific": "محدد",
      "conditions": "ظروف",
      "winds": "رياح",
      "rotate": "تدور",
      "forming": "مكونة",
      "horizontal": "أفقي",
      "tube": "أنبوب / مجرى",
      "updrafts": "تيارات هوائية صاعدة",
      "tilt": "تميل / تقلب",
      "vertical": "عمودي / رأسي",
      "column": "عمود",
      "reaching": "تصل إلى",
      "extreme": "أقصى / شديد",
      "speeds": "سرعات",
      "three": "ثلاثة",
      "hundred": "مئة",
      "miles": "أميال",
      "hour": "ساعة",
      "cause": "تسبب",
      "massive": "ضخم",
      "devastation": "دمار / خراب هائل",
      "destroying": "تدمير",
      "homes": "منازل",
      "lifting": "رفع / قذف",
      "cars": "سيارات",
      "effortlessly": "بدون مجهود / بسهولة",
      "rotation": "دوران"
    },
    quiz: [
      { question: "What air masses must collide to form a tornado?", options: ["Warm, moist air and cold, dry air", "Two identical hot desert wind currents", "Salty sea breezes and mountain snow"], answer: 0 },
      { question: "What is the maximum speed a tornado can reach?", options: ["Fifty miles per hour", "Over three hundred miles per hour", "Slightly below the speed of sound"], answer: 1 }
    ]
  },
  {
    day: 20,
    title: "Ancient Sky Navigation",
    difficulty: "B1.2 Intermediate",
    story: "Long before GPS and magnetic compasses, early sailors crossed vast oceans by looking at the night sky. They mapped the stars into recognizable shapes called constellations. In the Northern Hemisphere, sailors relied heavily on the North Star, which remains fixed in the sky to show true north. By using specialized instruments like astrolabes, navigators measured the angle between a celestial body and the horizon. This data allowed them to calculate their precise location and travel long distances safely.",
    target_words: ["constellations", "celestial", "orientation"],
    dictionary: {
      "long": "طويلاً",
      "before": "قبل",
      "gps": "نظام تحديد المواقع العالمي",
      "magnetic": "مغناطيسي",
      "compasses": "بوصلات",
      "early": "مبكر / أوائل",
      "sailors": "بحارة",
      "crossed": "عبروا",
      "vast": "شاسع / واسع",
      "oceans": "محيطات",
      "looking": "النظر إلى",
      "mapped": "رسموا خرائط لـ",
      "stars": "نجوم",
      "recognizable": "مألوف / سهل التعرف عليه",
      "shapes": "أشكال",
      "constellations": "كوكبات / مجموعات نجمية",
      "northern": "شمالي",
      "hemisphere": "نصف الكرة الأرضية",
      "relied": "اعتمدوا",
      "heavily": "بشدة",
      "north": "شمال",
      "star": "نجم",
      "remains": "يبقى",
      "fixed": "ثابت",
      "show": "يظهر / يدل على",
      "true": "حقيقي",
      "instruments": "أدوات / آلات",
      "astrolabes": "الأسطرلاب",
      "navigators": "ملاحون",
      "measured": "قاسوا",
      "angle": "زاوية",
      "celestial": "سماوي / فلكي",
      "body": "جرم سماوي / جسم",
      "horizon": "الأفق",
      "data": "بيانات",
      "allowed": "سمحت لهم",
      "calculate": "حساب",
      "precise": "دقيق",
      "location": "موقع",
      "travel": "السفر",
      "distances": "مسافات",
      "safely": "بأمان",
      "orientation": "توجيه / تحديد الاتجاه"
    },
    quiz: [
      { question: "Why was the North Star crucial for sailors in the Northern Hemisphere?", options: ["It was the brightest planet in the sky", "It remains fixed in the sky to show true north", "It changed colors depending on the wind"], answer: 1 },
      { question: "What instrument did early navigators use to measure star angles?", options: ["A modern digital telescope", "An astrolabe", "A mechanical barometer"], answer: 1 }
    ]
  },
  {
    day: 21,
    title: "Deciphering Hieroglyphs",
    difficulty: "B1.3 Intermediate",
    story: "For centuries, the beautiful carvings on ancient Egyptian temples remained a complete mystery. Nobody could read the picture-writing known as hieroglyphs. The breakthrough occurred in seventeen ninety-nine with the discovery of the Rosetta Stone. This stone slab contained a royal decree written in three different scripts: hieroglyphs, Demotic, and Greek. By comparing the known Greek text with the mysterious carvings, brilliant French linguist Jean-François Champollion finally deciphered the symbols in eighteen twenty-two, unlocking thousands of years of Egyptian history.",
    target_words: ["deciphered", "inscriptions", "symbols"],
    dictionary: {
      "centuries": "قرون",
      "beautiful": "جميل",
      "carvings": "نقوش / منحوتات",
      "ancient": "قديم",
      "egyptian": "مصري",
      "temples": "معابد",
      "remained": "بقيت",
      "complete": "كامل",
      "mystery": "غموض / لغز",
      "nobody": "لا أحد",
      "read": "يقرأ",
      "picture-writing": "الكتابة التصويرية",
      "hieroglyphs": "الهيروغليفية",
      "breakthrough": "إنجاز / طفرة",
      "occurred": "حدثت / وقعت",
      "discovery": "اكتشاف",
      "rosetta": "رشيد (حجر)",
      "stone": "حجر",
      "slab": "لوح / لوحة حجرية",
      "contained": "احتوى على",
      "royal": "ملكي",
      "decree": "مرسوم / قرار",
      "written": "مكتوب",
      "three": "ثلاثة",
      "different": "مختلف",
      "scripts": "خطوط / لغات مكتوبة",
      "demotic": "الديموطيقية",
      "greek": "اليونانية",
      "comparing": "مقارنة",
      "text": "نص",
      "linguist": "عالم لغوي",
      "jean-françois": "جان فرانسوا",
      "champollion": "شامبليون",
      "finally": "أخيراً",
      "deciphered": "فك شفرة / ترجم رموز",
      "symbols": "رموز",
      "eighteen": "ثمانية عشر",
      "unlocking": "فتح / كشف أسرار",
      "history": "تاريخ",
      "inscriptions": "نقوش / كتابات أثرية"
    },
    quiz: [
      { question: "Why was the Rosetta Stone key to unlocking hieroglyphs?", options: ["It contained a maps of hidden gold tombs", "It had the same royal decree written in three scripts, including Greek", "It was written by Tutankhamun himself"], answer: 1 },
      { question: "Who successfully deciphered the symbols in 1822?", options: ["Alan Turing", "Jean-François Champollion", "Marcus Aurelius"], answer: 1 }
    ]
  },
  {
    day: 22,
    title: "The History of Currency",
    difficulty: "B1.3 Intermediate",
    story: "Before the invention of currency, early human societies relied on bartering, which meant trading goods directly, like exchanging wheat for cows. However, bartering was highly inconvenient because both traders had to want what the other offered. To solve this, ancient civilizations introduced standardized currency. The earliest coins were minted in Lydia around six hundred BC using a natural mixture of gold and silver. Centuries later, China created paper banknotes to make large transactions lighter, forever changing global economic development.",
    target_words: ["currency", "standardized", "transactions"],
    dictionary: {
      "before": "قبل",
      "invention": "اختراع",
      "currency": "عملة / نقد",
      "early": "مبكر",
      "human": "بشري",
      "societies": "مجتمعات",
      "relied": "اعتمدت",
      "bartering": "المقايضة",
      "meant": "يعني",
      "trading": "تبادل تجاري",
      "goods": "سلع / بضائع",
      "directly": "مباشرة",
      "exchanging": "تبادل",
      "wheat": "قمح",
      "cows": "أبقار",
      "however": "ومع ذلك",
      "highly": "للغاية",
      "inconvenient": "غير مريح / غير ملائم",
      "traders": "تجار",
      "offered": "عرضه",
      "solve": "حل",
      "civilizations": "حضارات",
      "introduced": "قدمت / أدخلت",
      "standardized": "موحد / قياسي",
      "earliest": "أقدم",
      "coins": "عملات معدنية",
      "minted": "سُكت",
      "lydia": "ليديا (مملكة قديمة)",
      "around": "حوالي",
      "six": "ستة",
      "hundred": "مئة",
      "bc": "قبل الميلاد",
      "natural": "طبيعي",
      "mixture": "مزيج",
      "gold": "ذهب",
      "silver": "فضة",
      "centuries": "قرون",
      "later": "لاحقاً",
      "china": "الصين",
      "created": "صنعت / ابتكرت",
      "paper": "ورقي",
      "banknotes": "أوراق نقدية / بنكنوت",
      "make": "جعل",
      "large": "كبير / ضخم",
      "transactions": "معاملات / صفقات مالية",
      "lighter": "أخف وزناً",
      "forever": "إلى الأبد",
      "changing": "تغيير",
      "economic": "اقتصادي",
      "development": "تنمية / تطور"
    },
    quiz: [
      { question: "What is bartering?", options: ["Exchanging goods directly without money", "Printing paper notes in central banks", "Borrowing gold from kings"], answer: 0 },
      { question: "Why did ancient China introduce paper banknotes?", options: ["Because they did not have gold metals", "To make large financial transactions lighter", "To use them as decorative wall art"], answer: 1 }
    ]
  },
  {
    day: 23,
    title: "How We See Color",
    difficulty: "B1.3 Intermediate",
    story: "The human eye is an incredibly complex biological camera. When we look at an object, light bounces off its surface and enters our eyes. Special light-sensitive receptors, called cones, are located on the retina at the back of the eye. We possess three types of cones, each tuned to different wavelengths: red, green, and blue. These receptors convert light waves into electric signals. The brain's visual cortex interprets these signals instantly, allowing us to experience the rich color perception of the world around us.",
    target_words: ["receptors", "wavelengths", "perception"],
    dictionary: {
      "human": "بشري",
      "eye": "عين",
      "incredibly": "بشكل لا يصدق",
      "complex": "معقد",
      "biological": "بيولوجي",
      "camera": "كاميرا",
      "look": "ينظر",
      "object": "شيء / مجسم",
      "light": "ضوء",
      "bounces": "يرتد / ينعكس",
      "surface": "سطح",
      "enters": "يدخل",
      "special": "خاص",
      "light-sensitive": "حساس للضوء",
      "receptors": "مستقبلات",
      "called": "تدعى",
      "cones": "مخاريط (خلايا بصرية)",
      "located": "تقع",
      "retina": "شبكية العين",
      "back": "خلف / مؤخرة",
      "possess": "نمتلك",
      "three": "ثلاثة",
      "types": "أنواع",
      "each": "كل منها",
      "tuned": "مضبوط / متوافق",
      "wavelengths": "أطوال موجية",
      "red": "أحمر",
      "green": "أخضر",
      "blue": "أزرق",
      "convert": "تحول",
      "waves": "موجات",
      "electric": "كهربائي",
      "signals": "إشارات",
      "brain": "دماغ",
      "visual": "بصري",
      "cortex": "قشرة (الدماغ)",
      "interprets": "يفسر / يترجم",
      "instantly": "فوراً",
      "allowing": "يسمح لـ",
      "rich": "غني",
      "perception": "إدراك / فهم حسي",
      "world": "عالم"
    },
    quiz: [
      { question: "What are 'cones' in the human eye?", options: ["Small bones that help us hear", "Light-sensitive receptors that detect colors", "Muscle fibers that focus the lens"], answer: 1 },
      { question: "What wavelengths of light are our three types of cones tuned to?", options: ["Yellow, orange, and purple", "Red, green, and blue", "Infrared and ultraviolet"], answer: 1 }
    ]
  },
  {
    day: 24,
    title: "The Indestructible Tardigrade",
    difficulty: "B1.3 Intermediate",
    story: "Tardigrades, commonly known as water bears, are microscopic animals famous for their extreme survival skills. These tiny, eight-legged creatures can survive in boiling water, freezing temperatures of deep space, and intense radioactive exposure. When environmental conditions become dangerous, tardigrades enter a state called cryptobiosis. They expel almost all water from their bodies and curl into a dry ball, pausing their metabolism. In this inactive state, they can survive for decades, waking up healthy when placed in fresh water.",
    target_words: ["extreme", "microscopic", "survive"],
    dictionary: {
      "tardigrades": "تارديغرادا / بطيئات المشية",
      "commonly": "شائعاً / عادة",
      "known": "معروف",
      "water": "ماء",
      "bears": "دببة",
      "microscopic": "مجهري / دقيق جداً",
      "animals": "حيوانات",
      "famous": "مشهورة",
      "extreme": "أقصى / شديد للغاية",
      "survival": "البقاء على قيد الحياة",
      "skills": "مهارات",
      "tiny": "صغير جداً",
      "eight-legged": "ثماني الأرجل",
      "creatures": "مخلوقات",
      "survive": "تنجو / تبقى حية",
      "boiling": "مغلي",
      "freezing": "متجمد",
      "temperatures": "درجات حرارة",
      "space": "فضاء",
      "intense": "شديد",
      "radioactive": "إشعاعي",
      "exposure": "تعرض",
      "environmental": "بيئي",
      "conditions": "ظروف",
      "become": "تصبح",
      "dangerous": "خطيرة",
      "enter": "تدخل",
      "state": "حالة",
      "cryptobiosis": "الحياة الخفية / السبات الشديد",
      "expel": "تطرد / تخرج",
      "almost": "تقريباً",
      "bodies": "أجسامها",
      "curl": "تلتف / تتقوقع",
      "dry": "جاف",
      "ball": "كرة",
      "pausing": "إيقاف مؤقت",
      "metabolism": "التمثيل الغذائي / الأيض",
      "inactive": "غير نشط",
      "decades": "عقود",
      "waking": "الاستيقاظ",
      "up": "أعلى",
      "healthy": "بصحة جيدة",
      "placed": "توضع"
    },
    quiz: [
      { question: "What is cryptobiosis?", options: ["A dangerous viral disease", "An inactive state where water is expelled and metabolism pauses", "The process of building microscopic homes"], answer: 1 },
      { question: "Where can tardigrades survive according to the story?", options: ["Only in freshwater tropical rivers", "Boiling water, deep space, and radioactive exposure", "Only inside active volcanoes"], answer: 1 }
    ]
  },
  {
    day: 25,
    title: "Vertical Farming",
    difficulty: "B1.3 Intermediate",
    story: "As urban populations grow, traditional agriculture faces severe land and water shortages. To solve this problem, scientists developed vertical farming. Instead of planting crops in horizontal fields, plants are grown in vertically stacked layers inside controlled indoor warehouses. These modern facilities utilize LED lighting instead of sunlight and computerized hydroponic systems that deliver nutrient-rich water directly to roots. By using ninety-five percent less water and zero pesticides, vertical farming offers a high-yield, continuous year-round method to produce local food sustainably.",
    target_words: ["vertical", "sustainability", "hydroponics"],
    dictionary: {
      "urban": "حضري / مدني",
      "populations": "سكان",
      "grow": "ينمون / يزدادون",
      "traditional": "تقليدي",
      "agriculture": "زراعة",
      "faces": "تواجه",
      "severe": "شديد / قاسٍ",
      "land": "أرض",
      "water": "ماء",
      "shortages": "نقص / شح",
      "solve": "حل",
      "problem": "مشكلة",
      "scientists": "علماء",
      "developed": "طوروا",
      "vertical": "عمودي / رأسي",
      "farming": "زراعة",
      "instead": "بدلاً من",
      "planting": "زراعة / غرس",
      "crops": "محاصيل",
      "horizontal": "أفقي",
      "fields": "حقول",
      "grown": "تُزرع / تنمو",
      "vertically": "عمودياً",
      "stacked": "مكدسة / مرتبة فوق بعضها",
      "layers": "طبقات",
      "inside": "داخل",
      "controlled": "متحكم بها",
      "indoor": "داخلي / مغلق",
      "warehouses": "مستودعات / مخازن",
      "modern": "حديث",
      "facilities": "منشآت / مرافق",
      "utilize": "تستخدم / توظف",
      "led": "إل إي دي",
      "lighting": "إضاءة",
      "sunlight": "ضوء الشمس",
      "computerized": "محوسب",
      "hydroponic": "مائي / زراعة مائية",
      "systems": "أنظمة",
      "deliver": "توصل / تمد",
      "nutrient-rich": "غني بالمغذيات",
      "directly": "مباشرة",
      "roots": "جذور",
      "using": "استخدام",
      "less": "أقل",
      "zero": "صفر / لا يوجد",
      "pesticides": "مبيدات حشرية",
      "offers": "تقدم",
      "high-yield": "إنتاجية عالية",
      "continuous": "مستمر",
      "year-round": "على مدار السنة",
      "method": "طريقة / أسلوب",
      "produce": "إنتاج",
      "local": "محلي",
      "food": "طعام",
      "sustainably": "بشكل مستدام",
      "sustainability": "الاستدامة",
      "hydroponics": "الزراعة المائية"
    },
    quiz: [
      { question: "How are plants stacked in vertical farms?", options: ["In deep underground tunnels", "In vertically stacked layers indoors", "In floating greenhouses"], answer: 1 },
      { question: "What is an environmental advantage of vertical farming?", options: ["It uses ninety-five percent less water and zero pesticides", "It relies entirely on heavy rainfall", "It makes crops taste like sugar"], answer: 0 }
    ]
  },
  {
    day: 26,
    title: "The Mariana Trench",
    difficulty: "B1.3 Intermediate",
    story: "Deep in the western Pacific Ocean lies the Mariana Trench, the deepest place on Earth. It reaches a maximum depth of nearly thirty-six thousand feet, which is deeper than Mount Everest is tall. This abyssal environment is characterized by absolute darkness, freezing water, and crushing pressure that is one thousand times greater than at sea level. Despite these extreme conditions, robotic submarine cameras have captured images of bizarre lifeforms, such as transparent fish and giant amoebas, expanding our understanding of biological survival.",
    target_words: ["trench", "abyssal", "pressure"],
    dictionary: {
      "deep": "عميق",
      "western": "غربي",
      "pacific": "الهادئ",
      "ocean": "محيط",
      "lies": "يقع",
      "mariana": "ماريانا",
      "trench": "خندق",
      "deepest": "الأعمق",
      "place": "مكان",
      "earth": "الأرض",
      "reaches": "يصل إلى",
      "maximum": "أقصى / حد أقصى",
      "depth": "عمق",
      "nearly": "تقريباً",
      "thirty-six": "ستة وثلاثون",
      "thousand": "ألف",
      "feet": "أقدام",
      "deeper": "أعمق",
      "tall": "طويل / مرتفع",
      "abyssal": "سحيق / عميق جداً",
      "environment": "بيئة",
      "characterized": "يتميز بـ",
      "absolute": "مطلق",
      "darkness": "ظلام",
      "freezing": "متجمد",
      "crushing": "ساحق",
      "pressure": "ضغط",
      "one": "واحد",
      "times": "مرات / أضعاف",
      "greater": "أكبر / أعظم",
      "sea": "البحر",
      "level": "مستوى",
      "despite": "على الرغم من",
      "conditions": "ظروف",
      "robotic": "روبوتية / آلي",
      "submarine": "غواصة",
      "cameras": "كاميرات",
      "captured": "التقطت",
      "images": "صور",
      "bizarre": "غريب / عجيب",
      "lifeforms": "أشكال الحياة",
      "transparent": "شفاف",
      "fish": "سمك",
      "giant": "عملاق",
      "amoebas": "أميبيات / أميبا",
      "expanding": "توسيع",
      "understanding": "فهم",
      "biological": "بيولوجي",
      "survival": "البقاء"
    },
    quiz: [
      { question: "How deep is the Mariana Trench compared to Mount Everest?", options: ["It is half as deep as Everest is tall", "It is deeper than Mount Everest is tall", "They are exactly the same size"], answer: 1 },
      { question: "What is the water pressure like at the bottom of the trench?", options: ["Identical to a swimming pool", "One thousand times greater than at sea level", "Zero because of the depth"], answer: 1 }
    ]
  },
  {
    day: 27,
    title: "Evolution of Instruments",
    difficulty: "B1.3 Intermediate",
    story: "Since ancient times, humans have created musical instruments to express emotions and share folklore. The earliest instruments were simple animal bone flutes and hollow wooden drums. Over centuries, master artisans analyzed the physics of sound, learning how physical shapes influence sound wave vibrations. By introducing wooden bodies to create acoustic resonance and tensioned strings, they developed complex string instruments like the violin and piano. This acoustic evolution allowed musicians to play intricate compositions with incredible range, beauty, and emotional expression.",
    target_words: ["vibrations", "resonance", "acoustic"],
    dictionary: {
      "since": "منذ",
      "ancient": "قديم",
      "times": "أزمنة / أوقات",
      "humans": "البشر",
      "created": "ابتكروا / صنعوا",
      "musical": "موسيقي",
      "instruments": "آلات",
      "express": "التعبير عن",
      "emotions": "العواطف",
      "share": "مشاركة",
      "folklore": "الفولكلور / التراث الشعبي",
      "earliest": "أقدم",
      "simple": "بسيط",
      "animal": "حيوان",
      "bone": "عظم",
      "flutes": "ناي / مزامير",
      "hollow": "مجوف",
      "wooden": "خشبي",
      "drums": "طبول",
      "over": "على مر / خلال",
      "centuries": "قرون",
      "master": "ماهر / بارع",
      "artisans": "حرفيون / صناع",
      "analyzed": "حللوا",
      "physics": "فيزياء",
      "sound": "صوت",
      "learning": "تعلم",
      "how": "كيف",
      "physical": "مادي / فيزيائي",
      "shapes": "أشكال",
      "influence": "تؤثر على",
      "wave": "موجة",
      "vibrations": "اهتزازات / ذبذبات",
      "introducing": "إدخال / إضافة",
      "bodies": "صناديق / هياكل",
      "resonance": "رنين / صدى",
      "tensioned": "مشدودة",
      "strings": "أوتار",
      "developed": "طوروا",
      "complex": "معقد",
      "string": "وتري",
      "violin": "كمان",
      "piano": "بيانو",
      "acoustic": "صوتي / أكوستيك",
      "evolution": "تطور",
      "allowed": "سمح لـ",
      "musicians": "موسيقيون",
      "play": "عزف / يعزف",
      "intricate": "معقد / متشابك",
      "compositions": "مؤلفات موسيقية",
      "incredible": "مذهل",
      "range": "نطاق / مدى",
      "beauty": "جمال",
      "expression": "تعبير"
    },
    quiz: [
      { question: "What were the earliest musical instruments made from?", options: ["Melted copper and steel sheets", "Animal bones and hollow wood", "Digital synthesizer circuits"], answer: 1 },
      { question: "How did master artisans improve sound quality over time?", options: ["By painting instruments with bright colors", "By analyzing physics of sound vibrations and resonance", "By making instruments extremely heavy"], answer: 1 }
    ]
  },
  {
    day: 28,
    title: "Africa's Great Green Wall",
    difficulty: "B1.3 Intermediate",
    story: "South of the Sahara Desert, a vast strip of dry land known as the Sahel is facing severe desertification. To prevent fertile soil from turning into sand, eleven African countries launched the Great Green Wall initiative. The goal is to plant an eight thousand kilometer wall of trees across the entire width of Africa. By restoring millions of hectares of degraded soil, this sustainable green barrier helps combat climate change, provides local farming jobs, and ensures food security for millions of families.",
    target_words: ["desertification", "restoring", "initiative"],
    dictionary: {
      "south": "جنوب",
      "sahara": "الصحراء الكبرى",
      "desert": "صحراء",
      "vast": "شاسع",
      "strip": "شريط / حزام",
      "dry": "جاف",
      "land": "أرض",
      "known": "معروف",
      "sahel": "الساحل",
      "facing": "تواجه",
      "severe": "شديد",
      "desertification": "التصحر",
      "prevent": "منع",
      "fertile": "خصب",
      "soil": "تربة",
      "turning": "تحول",
      "sand": "رمل",
      "eleven": "إحدى عشرة",
      "african": "أفريقية",
      "countries": "دول",
      "launched": "أطلقت",
      "great": "العظيم / الكبير",
      "green": "الأخضر",
      "wall": "جدار / سور",
      "initiative": "مبادرة",
      "goal": "هدف",
      "plant": "زراعة",
      "eight": "ثمانية",
      "thousand": "ألف",
      "kilometer": "كيلومتر",
      "trees": "أشجار",
      "across": "عبر",
      "entire": "كامل",
      "width": "عرض",
      "restoring": "استعادة / ترميم",
      "millions": "ملايين",
      "hectares": "هكتارات",
      "degraded": "متدهور / تالف",
      "sustainable": "مستدام",
      "barrier": "حاجز",
      "helps": "يساعد",
      "combat": "محاربة / مكافحة",
      "climate": "مناخ",
      "change": "تغيير",
      "provides": "يوفر",
      "local": "محلي",
      "farming": "زراعي",
      "jobs": "وظائف",
      "ensures": "يضمن",
      "food": "غذاء",
      "security": "أمن"
    },
    quiz: [
      { question: "What environmental crisis is the Sahel region facing?", options: ["Frequent heavy flooding", "Severe desertification", "Rapid glacier melting"], answer: 1 },
      { question: "What is the main goal of the Great Green Wall initiative?", options: ["To build a physical brick defense wall", "To plant an 8,000 km wall of trees across Africa", "To excavate a giant irrigation canal"], answer: 1 }
    ]
  },
  {
    day: 29,
    title: "The Printing Press",
    difficulty: "B1.3 Intermediate",
    story: "In the mid-fifteenth century, German inventor Johannes Gutenberg developed a machine that transformed human history: the printing press. Before his invention, books had to be copied slowly by hand, making them incredibly rare and expensive. Gutenberg introduced movable metal type, which allowed workers to arrange letters quickly and print hundreds of identical pages in a single day. This massive technological leap accelerated literacy, allowed scientific knowledge to spread rapidly, and laid the foundation for the modern information age.",
    target_words: ["movable", "literacy", "dissemination"],
    dictionary: {
      "mid-fifteenth": "منتصف القرن الخامس عشر",
      "century": "قرن",
      "german": "ألماني",
      "inventor": "مخترع",
      "johannes": "يوهان",
      "gutenberg": "غوتنبرغ",
      "developed": "طور",
      "machine": "آلة",
      "transformed": "حوّلت",
      "human": "بشري",
      "history": "تاريخ",
      "printing": "طباعة",
      "press": "مطبعة",
      "before": "قبل",
      "invention": "اختراع",
      "books": "كتب",
      "copied": "تُنسخ",
      "slowly": "ببطء",
      "hand": "يدوية / باليد",
      "making": "مما جعل",
      "incredibly": "بشكل لا يصدق",
      "rare": "نادرة",
      "expensive": "غالية / باهظة",
      "introduced": "قدم / أدخل",
      "movable": "متحرك / قابل للتحريك",
      "metal": "معدن / معدني",
      "type": "حروف الطباعة / قوالب",
      "allowed": "سمح لـ",
      "workers": "عمال",
      "arrange": "ترتيب",
      "letters": "حروف",
      "quickly": "بسرعة",
      "print": "طباعة",
      "hundreds": "مئات",
      "identical": "متطابق",
      "pages": "صفحات",
      "single": "واحد / فردي",
      "day": "يوم",
      "massive": "ضخم / هائل",
      "technological": "تكنولوجي",
      "leap": "قفزة",
      "accelerated": "سرّعت",
      "literacy": "محو الأمية / القدرة على القراءة والكتابة",
      "scientific": "علمي",
      "knowledge": "معرفة",
      "spread": "انتشار",
      "rapidly": "بسرعة",
      "laid": "وضعت",
      "foundation": "أساس",
      "modern": "حديث",
      "information": "معلومات",
      "age": "عصر / عهد",
      "dissemination": "نشر / توزيع المعرفة"
    },
    quiz: [
      { question: "How were books created before Gutenberg's printing press?", options: ["Using early typewriter machines", "Copied slowly by hand", "Imported from advanced civilizations"], answer: 1 },
      { question: "What technology did Gutenberg introduce to speed up printing?", options: ["Movable metal type", "Steam-powered engines", "Chemical ink sprays"], answer: 0 }
    ]
  },
  {
    day: 30,
    title: "Bioluminescence",
    difficulty: "B1.3 Intermediate",
    story: "Bioluminescence is a magical biochemical process where living organisms produce and emit their own light. This phenomenal ability is commonly found in deep-sea creatures, such as anglerfish and jellyfish, as well as terrestrial insects like fireflies. To produce light, a chemical reaction occurs inside specialized cells, combining a substance called luciferin with oxygen in the presence of an enzyme. Organisms utilize this cold light for critical behaviors, including attracting mates, tricking prey, and startling dangerous predators in the pitch-black darkness.",
    target_words: ["bioluminescence", "chemical", "predators"],
    dictionary: {
      "bioluminescence": "التحلل الحيوي / التلألؤ البيولوجي",
      "magical": "ساحر / عجيب",
      "biochemical": "كيميائي حيوي",
      "process": "عملية",
      "where": "حيث",
      "living": "حي",
      "organisms": "كائنات حية",
      "produce": "تنتج",
      "emit": "تبعث / تطلق",
      "own": "خاص بها",
      "light": "ضوء",
      "phenomenal": "ظاهرة / استثنائي",
      "ability": "قدرة",
      "commonly": "شائعاً",
      "found": "موجود",
      "deep-sea": "أعماق البحار",
      "creatures": "مخلوقات",
      "anglerfish": "سمكة أبو الشص",
      "jellyfish": "قنديل البحر",
      "terrestrial": "برية / أرضي",
      "insects": "حشرات",
      "fireflies": "اليراعات / حشرات مضيئة",
      "chemical": "كيميائي",
      "reaction": "تفاعل",
      "occurs": "يحدث",
      "inside": "داخل",
      "specialized": "متخصصة",
      "cells": "خلايا",
      "combining": "دمج / جمع",
      "substance": "مادة",
      "luciferin": "لوسيفرين",
      "oxygen": "أكسجين",
      "presence": "وجود",
      "enzyme": "إنزيم",
      "utilize": "تستخدم",
      "cold": "بارد",
      "critical": "حاسمة / هامة",
      "behaviors": "سلوكيات",
      "including": "بما في ذلك",
      "attracting": "جذب",
      "mates": "أقران / شركاء التكاثر",
      "tricking": "خداع",
      "prey": "فريسة",
      "startling": "إخافة / إرباك",
      "dangerous": "خطير",
      "predators": "مفترسات",
      "pitch-black": "شديد الظلمة / حالك"
    },
    quiz: [
      { question: "What is bioluminescence?", options: ["Solar energy stored by plants", "A chemical reaction inside cells where living organisms emit light", "The reflection of moonlight on waves"], answer: 1 },
      { question: "What do deep-sea creatures use bioluminescence for?", options: ["To heat cold ocean water", "To attract mates, trick prey, and startle predators", "To navigate through rock caves only"], answer: 1 }
    ]
  }
];
